# Generated by Django 3.2.5 on 2021-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immi_fourm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
