# Generated by Django 3.2.5 on 2021-07-27 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immi_fourm', '0002_alter_forum_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
