# Generated by Django 3.2.5 on 2021-07-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immi_fourm', '0003_alter_forum_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='post_url',
            field=models.SlugField(null=True),
        ),
    ]
