# Generated by Django 3.2.5 on 2021-08-05 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immi_fourm', '0005_alter_forum_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_comment',
            name='like',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
