# Generated by Django 3.2.5 on 2021-08-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immi_fourm', '0006_forum_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_comment',
            old_name='like',
            new_name='all_like',
        ),
    ]
