# Generated by Django 3.2.5 on 2021-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immi_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nationality',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='program',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(max_length=255),
        ),
    ]
